# namespace-resourcequota.yml

apiVersion: v1
kind: ResourceQuota
metadata:
  name: memory-cpu-quota
  namespace: geolocation
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi


#
# create namespace first using -
# kubectl create namespace geolocation
#
# apply it using - 
# kubectl apply -f namespace-resourcequota.yml
# 
# check resourcequota -
# kubectl get resourcequotas --namespace=geolocation
#
# get details of resourcequota -
# kubectl describe resourcequotas memory-cpu-quota --namespace=geolocation
# 
# delete resourcequota - 
# kubectl delete resourcequotas memory-cpu-quota --namespace=geolocation
# 
# delete namespace -
# kubectl delete namespace geolocation
#
