apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 076892551558.dkr.ecr.us-east-1.amazonaws.com/geolocation_ecr_rep:latest
        ports:
          - containerPort: 80
            name: nginx-web-svc
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment-service
spec:
  selector:
    app: ngimx
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: nginx-web-svc


#we should be able to access the application using service IP 
