apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webserver
  namespace: default
spec:
  replicas: 3
  selector: 
        matchLabels:
               app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - name: webserver
          image: 076892551558.dkr.ecr.us-east-1.amazonaws.com/geolocation_ecr_rep:latest
          livenessProbe:
            exec:
              command:
              - cat 
              - /var/www/html/index.html
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 20
            failureThreshold: 3
          resources:
            requests: #request means minimum
              cpu: "500m"
              memory: "128Mi"
            limits: #limits means maximum
              cpu: "1000m"
              memory: "256Mi"
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
