apiVersion: v1
kind: Pod
metadata:
  name: utrains
  labels:
   app: utrains
spec:
  containers:
    - name: utrains-app
      image: 076892551558.dkr.ecr.us-east-1.amazonaws.com/geolocation_ecr_rep:latest
