# namespace-pod-quota.yml
#
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pod-quota
  namespace: geolocation
spec:
  hard:
    pods: "4"

#
# We are applying quota on number of pods 
# that can run inside a namespace. So if
# total number of running pods increases
# above 4, it will fail with quota error.
#
# create namespace geolocation -
# kubectl create namespace geolocation
#
# apply the quota on number of pods
# kubectl apply -f namespace-pod-quota.yml
#
# check the resource quota
# kubectl get resourcequotas --namespace=geolocation
#
# get details about resource quota
# kubectl describe resourcequotas pod-quota --namespace=geolocation
#
# delete resource quota
# kubectl delete resourcequotas pod-quota --namespace=geolocation
#

