# pod-simple-qos-burstable.yml
#
apiVersion: v1
kind: Pod
metadata:
  name: utrains
  namespace: geolocation
  labels:
   app: utrains
spec:
  containers:
    - name: utrains-app
      image: 076892551558.dkr.ecr.us-east-1.amazonaws.com/geolocation_ecr_rep:latest
      resources:
        limits:
          memory: "250Mi"
        requests:
          memory: "150Mi"
#
# Creating a simple pod. Which has apache
# configured inside it. There are memory request
# and memory limits restrictions. So pod will 
# initially be given 150Mi of physical memory, but
# it can burst upto 250Mi. If no other default limits
# are applied. So kubernetes can burst memory, if 
# needed. 
#
# QoS = Burstable
#
# create namespace geolocation -
# kubectl create namespace geolocation
#
# run the pod
# kubectl create -f pod-simple-qos-burstable.yml
#
# check the pod
# kubectl get pods --namespace=geolocation
#
# get details about pod
# kubectl describe pod/utrains --namespace=geolocation
# 
# Check the "QoS Class" value. 
#
# delete pod
# kubectl delete pod/utrains --namespace=geolocation
#
