# pod-with-preferred-node-affinity.yml
#
apiVersion: v1
kind: Pod
metadata:
  name: utrains
  namespace: geolocation
  labels:
   app: utrains
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: size
            operator: In
            values:
            - small
  containers:
    - name: utrains-app
      image: 076892551558.dkr.ecr.us-east-1.amazonaws.com/geolocation_ecr_rep:latest
      resources:
        limits:
          memory: "500Mi"
        requests:
          memory: "300Mi"

#
# This means that the pod will PREFER to get
# scheduled on a node that has a size=small label.
#
# First label one/more nodes with some kind of tag
# we are classifying our nodes as small, medium &
# heavy and the label name is "size" value can be
# "small / medium / heavy"
#
# First label nodes as small / medium:
# kubectl label nodes nodeone.example.com size=small
# kubectl label nodes nodetwo.example.com size=medium
#
# Confirm for the labels on nodes using:
#
# kubectl get nodes --show-labels 
#
# create namespace geolocation -
# kubectl create namespace geolocation
#
# run the pod
# kubectl create -f pod-with-preferred-node-affinity.yml
#
# check the pod
# kubectl get pods --namespace=geolocation --output=wide
#
# get details about pod
# kubectl describe pod/utrains --namespace=geolocation
#
# check for the node where its running, it should be
# PROBABLY on nodes with label "size=small"
# 
# delete pod
# kubectl delete pod/utrains --namespace=geolocation
#
# delete the labels
# kubectl label node nodeone.example.com size-
# kubectl label node nodetwo.example.com size-
#
