# pod-simple-lifecycle-events.yml
#
apiVersion: v1
kind: Pod
metadata:
  name: utrains
  namespace: geolocation
  labels:
   app: utrains
spec:
  containers:
    - name: utrains-app
      image: image: 076892551558.dkr.ecr.us-east-1.amazonaws.com/geolocation_ecr_rep:latest
      lifecycle:
        postStart:
          exec:
            command: ["/bin/sh", "-c", "useradd utrains -p redhat"]
        preStop:
          exec:
            command: ["/bin/sh","-c","rm -rf /home/utrains; userdel utrains"]
#
# Creating a simple pod. Which has apache
# configured inside it. The container inside the
# pod has handlers for the postStart and preStop events.
#
# postStart - postStart event is called immediately 
# after the Container is created 
#
# preStop - preStop event is called immediately
# before the Container is terminated
#
# Create namespace geolocation -
# kubectl create namespace geolocation
#
# Run the pod
# kubectl create -f pod-simple-lifecycle-events.yml
#
# Check the pod
# kubectl get pods --namespace=geolocation
#
# Go inside the pod to check user - utrains
# kubectl exec -it utrains --namespace=geolocation -- /bin/bash
# 
# Check inside /etc/passwd and you will find user - utrains
# tail /etc/passwd
# 
# Delete pod
# kubectl delete pod/utrains --namespace=geolocation
#
