# pod-for-specific-node.yml
#
apiVersion: v1
kind: Pod
metadata:
  name: utrains
  namespace: geolocation
  labels:
   app: utrains
spec:
  nodeName: nodeone.example.com #this will assign pod to specific node
  containers:
    - name: utrains-app
      image: image: 076892551558.dkr.ecr.us-east-1.amazonaws.com/geolocation_ecr_rep:latest
      resources:
        limits:
          memory: "500Mi"
        requests:
          memory: "300Mi"


#
# We are scheduling our pod to run on a SPECIFIC
# node - nodeone.example.com using
# "nodeName" setting
#
# create namespace geolocation -
# kubectl create namespace geolocation
#
# run the pod
# kubectl create -f pod-for-specific-node.yml
#
# check the pod
# kubectl get pods
#
# get details about pod
# kubectl describe pod/utrains --namespace=geolocation
#
# check for the node where its running
#
# delete pod
# kubectl delete pod/utrains --namespace=geolocation
#
