# pod-simple-qos-burstable.yml
#
apiVersion: v1
kind: Pod
metadata:
  name: utrains
  namespace: geolocation
  labels:
   app: utrains
spec:
  containers:
    - name: utrains-app
      image: 076892551558.dkr.ecr.us-east-1.amazonaws.com/geolocation_ecr_rep:latest
      resources:
        limits:
          memory: "250Mi"
          cpu: "400m"
        requests:
          memory: "250Mi"
          cpu: "400m"
#
# Creating a simple pod. Which has apache
# configured inside it. There are memory & cpu 
# restrictions. But both are same so kubernetes 
# cluster will guarantee that much of 
# resources to the pod, before running it on any node.
#
# QoS = Guaranteed
#
# create namespace geolocation -
# kubectl create namespace geolocation
#
# run the pod
# kubectl create -f pod-simple-qos-guaranteed.yml
#
# check the pod
# kubectl get pods --namespace=geolocation
#
# get details about pod
# kubectl describe pod/utrains --namespace=geolocation
# 
# Check the "QoS Class" value. 
#
# delete pod
# kubectl delete pod/utrains --namespace=geolocation
#
