# simple-pod.yml
apiVersion: v1

kind: Pod

metadata:
  name: webserver

spec:
  containers:
    - name: webserver
      image: 076892551558.dkr.ecr.us-east-1.amazonaws.com/geolocation_ecr_rep:latest
